
const formdata = [
    {
      createCard: true,
      completed: true,
    },
    {
        heading: "BE CSE SEM5",
        branch: "BE",
        department: "CSE",
        semester: "3",
        subject: "5",
        lab: "2",
        ExamType: "Model",
        completed: false,
      },
    {
        heading: "BTECH IT SEM5",
        branch: "BTECH",
        department: "IT",
        semester: "3",
        subject: "5",
        lab: "2",
        ExamType: "Model",
        completed: true,
      },
    {
      heading: "BE ECE SEM3",
      branch: "B.E",
      department: "I.T",
      semester: "3",
      subject: "5",
      lab: "2",
      ExamType: "Semster",
      completed: false,
    },
    {
      heading: "BE EEE SEM 3",
      branch: "B.E",
      department: "I.T",
      semester: "3",
      subject: "5",
      lab: "2",
      ExamType: "Semster",
      completed: true,
    },
    {
      heading: "BTECH IT SEM5",
      branch: "BTECH",
      department: "IT",
      semester: "3",
      subject: "5",
      lab: "2",
      ExamType: "Model",
      completed: true,
    },
    {
      heading: "BE EEE SEM 1",
      branch: "B.E",
      department: "EEE",
      semester: "3",
      subject: "5",
      lab: "2",
      ExamType: "Internal",
      completed: true,
    },
    ]
export default formdata

